//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Sale
    {
        public int OrderID { get; set; }
        public int EmpID { get; set; }
        public int CustID { get; set; }
        public int ProductID { get; set; }
        public decimal Amount { get; set; }
        public string PaymentType { get; set; }
        public int OrderStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
