//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PayID { get; set; }
        public int InvoiceID { get; set; }
        public int VendorID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
