//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll
    {
        public int PayrollID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> PayBegin { get; set; }
        public Nullable<System.DateTime> PayEnd { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public Nullable<int> AcctNumber { get; set; }
        public Nullable<int> RouteNumber { get; set; }
        public string BankName { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
